version: '3.8'

services:
  wazuh-loader-api:
    build: .
    container_name: wazuh-loader-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./config.json:/app/config.json:ro
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - wazuh-network

  # Valfri: Nginx reverse proxy för produktion
  nginx:
    image: nginx:alpine
    container_name: wazuh-loader-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - wazuh-loader-api
    restart: unless-stopped
    networks:
      - wazuh-network
    profiles:
      - production

networks:
  wazuh-network:
    driver: bridge
